### ISSUE TITLE
모바일 화면 뷰포트 대응

### ISSUE THREAD

**Issue by dplusic** [yingyeothon/1team-unity-client#13]
- 모바일에서 모든 타일이 보이지 않음
- 화면 스크롤을 통해 다른쪽도 볼 수 있게 하거나, 모바일 화면에 맞춰 타일들을 재배치 하는 방법을 생각해 볼 수 있음
- 현재 상태:
![Screenshot_2020-01-12-13-22-14-214_life yyt clickandmore](https://user-images.githubusercontent.com/880189/72216961-5ad67b80-356b-11ea-96e7-50a2e2c269d9.jpg)

**Comment by dplusic** [comment]
모바일 화면을 landscape 로 고정하면 됨.

**Comment by gasbank** [comment]
가로모드와 세로모드 모두 지원하도록 수정함. landscape 고정 다시 풀었음.

**Comment by dplusic** [comment]
오오.. 그렇게 하는거군요!
:+1:
