### ISSUE TITLE
레벨업 가능할 때를 클라에서 표시하기 위한 프로토콜 정의

### ISSUE THREAD

**Issue by dplusic** [yingyeothon/1team-unity-client#4]
"클라에서 표시"라 함은 이펙트 등을 뜻함.

방안1: 어느 value 에 levelup 가능한지에 대한 데이터 테이블을, 게임 시작 할때 서버에서 클라로 넘겨준다.

방안2: levelup 가능 여부를 서버 상태로 관리하고 클라로 전달한다.

**Comment by lacti** [comment]
2 :+1:
