### ISSUE TITLE
levelup request 를 click request 로 통합

### ISSUE THREAD

**Issue by dplusic** [yingyeothon/1team-unity-client#5]

**Comment by lacti** [comment]
큰 의견 없으면 현 상태 그대로 가시죠

**Comment by dplusic** [comment]
@lacti 
앗.. 의견 주신것을 못봤네요..
레벨업 가능한 시점을 데이터를 서버에서 관리하다보니,
클라에서는 levelup request 를 보낼 시점을 모르게 되었습니다.겠스

전에 얘기한데로 levelup 가능 여부를 tile 에 심어서 보내줄 수 있겠지만
작업이 비슷해보여서 이쪽으로 진행해보겠습니다.

**Comment by dplusic** [comment]
@lacti  는 fake.. 그대로 갑니다....
